<a href="https://colab.research.google.com/github/badhayearushi-alt/Python---Basic---Projects/blob/main/20_Optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

Saving House Price Prediction Dataset.csv to House Price Prediction Dataset (1).csv

In [3]:
df_name = list(uploaded.keys())[0]
df = pd.read_csv(df_name)

X = df.drop("Price", axis=1)
Y = df["Price"]

print("X Shape:", X.shape)
print("Y Shape:", Y.shape)

X Shape: (2000, 9)
Y Shape: (2000,)

In [5]:
 cat_cols = X.select_dtypes(include="object").columns

 X = pd.get_dummies(X, columns=cat_cols)

 X.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,1,1360,5,4,3,1970,True,False,False,False,True,False,False,False,True,False
1,2,4272,5,4,3,1958,True,False,False,False,True,False,False,False,True,False
2,3,3592,2,2,3,1938,True,False,False,False,False,False,True,False,True,False
3,4,966,4,2,2,1902,False,False,True,False,False,True,False,False,False,True
4,5,4926,1,4,2,1975,True,False,False,False,False,True,False,False,False,True

In [7]:
from sklearn.preprocessing import StandardScaler

num_cols = ["Id", "Area", "Bedrooms", "Bathrooms", "Floors", "YearBuilt"]

scaler = StandardScaler()

X[num_cols] = scaler.fit_transform(X[num_cols])

X.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,-1.731185,-1.101471,1.401791,1.305568,1.244151,0.238155,True,False,False,False,True,False,False,False,True,False
1,-1.729453,1.147485,1.401791,1.305568,1.244151,-0.095942,True,False,False,False,True,False,False,False,True,False
2,-1.727721,0.622317,-0.704581,-0.498326,1.244151,-0.652770,True,False,False,False,False,False,True,False,True,False
3,-1.725989,-1.405759,0.699667,-0.498326,0.008035,-1.655061,False,False,True,False,False,True,False,False,False,True
4,-1.724257,1.652574,-1.406705,1.305568,0.008035,0.377363,True,False,False,False,False,True,False,False,False,True

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.33,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Y_train:", Y_train.shape)
print("Y_test:", Y_test.shape)

X_train: (1340, 16)
X_test: (660, 16)
Y_train: (1340,)
Y_test: (660,)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, Y_train)

print("Intercept:", model.intercept_)
print("\nCoefficients:", model.coef_)

Intercept: 530507.9132761922

Coefficients: [ -5260.30276531  -1094.67163256   3023.60283364 -11731.77134152
  21278.73975838    698.36872415   7437.51033506   -947.21402283
   7393.49390228 -13883.79021451   -283.96579724   7795.10659858
 -15785.14565808   8274.00485674  -3396.10710937   3396.10710937]

In [11]:
 Y_pred = model.predict(X_test)

 print("Predicted Prices:")
 print(Y_pred[:10])

Predicted Prices:
[494429.11730577 537179.07589112 474702.23728936 544594.5342291
 560298.20362759 522069.63346423 515031.22675846 551174.07604418
 558571.61703856 554727.91718024]

In [13]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, Y_pred)

print("R² Score:", r2)

R² Score: -0.011363758036900595

In [15]:
import joblib

joblib.dump(model, "HousePriceModel.pkl")
joblib.dump(scaler, "Scaler.pkl")

print("Model saved successfully.")

Model saved successfully.